services:
  - type: web
    name: facilita-api
    env: python
    plan: free  # Pode mudar para 'starter' ou outro plano pago se necessário
    region: oregon  # Escolha a região mais próxima (ex.: 'oregon', 'frankfurt')
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0  # Versão do Python (ajuste conforme necessário)
      - key: FLASK_ENV
        value: production